Pavlo
PavloTarnovetskyi/Flaskapp pull request #5
Opened 2022-09-14 12:54 UTC by PavloTarnovetskyi

**What is this change?**
In main.tf changed the protocol to '-1', deleted deploying script, and wrote deploying task in playbook.yml

**Why is this important?**
used better deploying practice

**How has this been tested?**
manually from localhost

**How can this be rolled back?**

Rollback can be performed by reverting these changes in source control and redeploying via standard deployment mechanisms. This change is safe to roll back.

**Are there any security risks introduced by this change?**

2022-09-14 13:52 UTC, antoniakstas requested changes

2022-09-14 13:52 UTC, antoniakstas commented on ansible/playbook.yml
>      shell: |
this needs to be updated to use corresponding ansible modules. For example for [apt](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html) for [systemctl](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html) etc..

2022-09-14 14:16 UTC, PavloTarnovetskyi commented on ansible/playbook.yml
>      shell: |
ok

2022-09-15 10:42 UTC, nos373737 commented on ansible/playbook.yml
>      shell: |
@antoniakstas could you please review?

2022-09-15 10:49 UTC, antoniakstas commented on ansible/playbook.yml
>      become: yes
there are also modules for [systemctl](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html) and [docker container](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module)

2022-09-15 10:52 UTC, nos373737 commented on ansible/playbook.yml
>      become: yes
As I understand you need to get out of using systemctl via ansible modules and docker commands the same

2022-09-15 16:07 UTC, antoniakstas reviewed
what is the file .DS_Store?

2022-09-16 08:21 UTC, antoniakstas commented on DaS/flaskapp_diagrama.py
> +
```suggestion

```

2022-09-16 08:34 UTC, antoniakstas approved these changes
lgtm

2022-09-16 08:35 UTC, merged